### ISSUE TITLE
Which is the current version?

### ISSUE THREAD

**Issue by mv10-work** [OrleansContrib/Orleans.Http#31]
There are two Orleans.Http packages out there on NuGet. This repo readme says 1.1.0 is the latest which seems to match the package attributed to Gutemberg (with the correct icon), but there is a higher-versioned 1.4.1 from OrleansContrib that looks older. Very confusing.

![image](https://user-images.githubusercontent.com/54578900/68968453-9396e600-07b0-11ea-82b4-59531b439888.png)

**Comment by galvesribeiro** [comment]
Hello! The first one is the current version. The last one is deprecated.
