### ISSUE TITLE
support .net core 2.2 and swagger 

### ISSUE THREAD

**Issue by vivid216** [OrleansContrib/Orleans.Http#36]
nuget release support both .net core 2.2 and 3.0 & swagger support is very very very want...

**Comment by galvesribeiro** [comment]
Hello @vivid216!

Swagger support is tracked by #25. The package uses ASP.Net Core 3.0 endpoint routing and that requires the package to target `netcore3.0`. There is no way to support 2.2.

Please follow #25 that will let you know when Swagger support is available.

Thanks!
